definitions:
  types.Category:
    properties:
      image:
        type: string
      title:
        type: string
    type: object
  types.Loginuser:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  types.Menu:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  types.PasswordReset:
    properties:
      email:
        type: string
      new_password:
        type: string
      old_password:
        type: string
    required:
    - email
    - new_password
    - old_password
    type: object
  types.RegisterUser:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - phone
    type: object
  types.Table:
    properties:
      number_of_guests:
        type: integer
      table_number:
        type: integer
      table_status:
        type: string
    type: object
info:
  contact: {}
paths:
  /categeory/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete a category
      tags:
      - Admin
    get:
      consumes:
      - application/json
      description: Get a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get a category
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update a category
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/types.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update a category
      tags:
      - Admin
  /categories:
    get:
      consumes:
      - application/json
      description: Get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all categories
      tags:
      - Global
    post:
      consumes:
      - application/json
      description: Create a category
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/types.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create a category
      tags:
      - Admin
  /login:
    post:
      consumes:
      - application/json
      description: user can login by giving their email and password
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.Loginuser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: User Login
      tags:
      - Auth
  /logout:
    post:
      consumes:
      - application/json
      description: user can logout by giving their user_id
      parameters:
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: User Logout
      tags:
      - Auth
  /menu:
    get:
      consumes:
      - application/json
      description: Get all menus
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all menus
      tags:
      - Global
    post:
      consumes:
      - application/json
      description: Create a menu
      parameters:
      - description: Menu object
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/types.Menu'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a menu
      tags:
      - Admin
  /menu/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a menu
      parameters:
      - description: Menu ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a menu
      tags:
      - Admin
    get:
      consumes:
      - application/json
      description: Get a menu
      parameters:
      - description: Menu ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get a menu
      tags:
      - Global
    put:
      consumes:
      - application/json
      description: Update a menu
      parameters:
      - description: Menu ID
        in: path
        name: id
        required: true
        type: string
      - description: Menu object
        in: body
        name: menu
        required: true
        schema:
          $ref: '#/definitions/types.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update a menu
      tags:
      - Admin
  /register:
    post:
      consumes:
      - application/json
      description: user can signup by giving their details
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.RegisterUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: User Signup
      tags:
      - Auth
  /reset-password:
    post:
      consumes:
      - application/json
      description: Reset user password
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.PasswordReset'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Reset Password
      tags:
      - Auth
  /table:
    get:
      consumes:
      - application/json
      description: Get all tables
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all tables
      tags:
      - Global
    post:
      consumes:
      - application/json
      description: Create a table
      parameters:
      - description: Table
        in: body
        name: table
        required: true
        schema:
          $ref: '#/definitions/types.Table'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a table
      tags:
      - Admin
  /table/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a table
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a table
      tags:
      - Admin
    get:
      consumes:
      - application/json
      description: Get a table
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get a table
      tags:
      - Global
    put:
      consumes:
      - application/json
      description: Update a table
      parameters:
      - description: Table ID
        in: path
        name: id
        required: true
        type: string
      - description: Table
        in: body
        name: table
        required: true
        schema:
          $ref: '#/definitions/types.Table'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update a table
      tags:
      - Admin
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create User
      tags:
      - Admin
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - Admin
    get:
      consumes:
      - application/json
      description: Get a user Details by ID
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get a  User
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user details
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - User
swagger: "2.0"
